export { RoomVibezViewer, StaleLoadError, loadProductRoot, type ViewerOptions, type ViewerStatus } from './RoomVibezViewer';
export { LIGHT_PRESETS, findPreset, type LightPreset } from './presets';
export { buildPartsList, findMaterial, materialsForSlot, validateProduct } from './library';
export {
  discoverSlots,
  resolveSlotId,
  bindUntaggedToFallback,
  ensureMeshNormals,
  meshesMissingUv,
  resolveBindings,
  type BindingRejectReason,
  type ResolvedBindings,
} from './slots';
export {
  UPLOAD_SLOT_CATEGORIES,
  attachTextureToMaterial,
  createMaterialFromTexture,
  createProductFromModelFiles,
  createProductFromObjPackage,
  isMeshUploadFile,
  isModelFile,
  isMtlFile,
  isObjFile,
  isObjSidecarFile,
  isTextureFile,
  slotIdFromLabel,
  type ModelUploadResult,
  type ObjImportResult,
  type ObjImportWarnings,
  type TextureMapRole,
} from './uploads';
export {
  ModuleContractError,
  createProductFromModuleAsset,
  defaultThreeBareImportUrls,
  getModuleFactory,
  importModuleFile,
  isModuleFile,
  registerModuleFactory,
  resolveModuleAsset,
  rewriteThreeBareImports,
  type CreateAssetFn,
  type ResolvedModuleAsset,
  type ThreeBareImportUrls,
} from './modules';
export {
  applyPackAppearance,
  associatePackFiles,
  createProductFromPack,
  defaultsFromMeta,
  ensurePackZoneSlots,
  finishToPbr,
  inferPackMapping,
  probeVertexColorZones,
  remapVertexColors,
  resolveModulePackMeta,
  resolvePackColors,
  splitVertexColorZones,
  type ModulePackMeta,
  type PackLoadResult,
  type PackMappingMode,
  type PackParamSchema,
  type PackStatus,
  type SplitZonesResult,
} from './packs';
export {
  DEFAULT_CEILING_HEIGHT_M,
  DEFAULT_DOOR,
  DEFAULT_WALL_THICKNESS_M,
  DEFAULT_WINDOW,
  ROOM_PRESETS,
  STORAGE_KEY,
  addOpening,
  addPlacement,
  cloneRoomGraphSeed,
  createRectangularRoom,
  formatLength,
  fromMeters,
  loadPersistedRoomGraph,
  normalizeRoomGraph,
  openingOffsetFromHit,
  persistRoomGraph,
  removeOpening,
  removePlacement,
  roomBounds,
  setRoomSurfaceMaterials,
  toMeters,
  updateOpening,
  updatePlacement,
  validateOpening,
  wallLength,
  type ConfirmStatus,
  type DisplayUnit,
  type OpeningEntity,
  type OpeningInput,
  type OpeningType,
  type PlacementEntity,
  type ProvenanceKind,
  type RoomEntity,
  type RoomGraph,
  type RoomProvenance,
  type RoomSizeInput,
  type SourceAsset,
  type SourceAssetKind,
  type Vec2,
  type WallEntity,
} from './roomGraph';
export {
  FIXTURE_CANDIDATES_URL,
  FIXTURE_PREVIEW_URL,
  builtInFixtureCandidates,
  candidatesOverlaySvg,
  confirmImportToRoomGraph,
  kindFromFilename,
  loadFixtureCandidates,
  parseCandidatesPayload,
  scaleFactorFromKnownLength,
  setCandidateAccepted,
  setScaleFactor,
  sha256Hex,
  startImportJob,
  type ImportCandidates,
  type ImportJob,
  type OpeningCandidate,
  type RoomCandidate,
  type WallCandidate,
} from './dwgImport';
export {
  TEMPLATE_STORAGE_KEY,
  deleteTemplate,
  instantiateTemplate,
  loadTemplates,
  persistTemplates,
  saveGraphAsTemplate,
  type RoomTemplate,
} from './roomTemplates';
export { buildRoomScene, buildWallMesh, buildWallFootprint, buildOpeningPlaceholder, meshStandardFromLibrary, floorPolygonBounds, outerFloorPolygon, wallCenterlinePolygon, wallCutawayPlane, DEFAULT_FLOOR_COLOR, DEFAULT_WALL_COLOR, FLOOR_SLAB_DEPTH_M, FLOOR_TOP_EPS_M, WALL_FOOT_EPS_M, type BuiltRoomScene, type RoomMeshMaterials, type WallCutawayPlane } from './roomMesh';
export { RoomHistory } from './roomHistory';
export {
  checkPlacementCollision,
  footprintFromObject,
  footprintFromPlacement,
  formatCollisionWarn,
  pointInFloorPolygon,
  pointInRoom,
  wallFootprint,
  type CollisionReport,
} from './roomCollision';
export { snapPlacementToWall } from './roomSnap';
export { buildPlanSvg, planSvgToPngDataUrl } from './roomPlan';
export {
  addDrawPoint,
  closeDistance,
  commitDrawSession,
  createDrawSession,
  snapOrthogonal,
  type DrawSession,
} from './freeformWalls';
export {
  downloadTextFile,
  exportProjectJson,
  idbGet,
  idbSet,
  loadProjectFromIdb,
  parseProjectJson,
  persistProjectToIdb,
  serializeProject,
} from './projectIO';
export {
  formatMjsGuardMessage,
  isMjsLoadingEnabled,
  MJS_ENABLED_KEY,
  scanMjsSource,
  setMjsLoadingEnabled,
} from './mjsGuardrails';
export {
  confirmUnderlayToRoomGraph,
  isPdfPlanFile,
  isRasterPlanFile,
  startUnderlayJob,
  type UnderlayJob,
} from './planUnderlay';
export {
  createThumbnailRenderer,
  type ThumbnailRenderer,
  type ThumbnailRendererOptions,
  type ThumbnailStats,
} from './thumbnails';
export {
  QUARANTINE_STORAGE_KEY,
  ROOM_SIZE_ERROR_MESSAGE,
  RoomSizeError,
  discardQuarantinedRoomGraph,
  invalidRoomSizeFields,
  loadPersistedRoomGraphOrQuarantine,
  quarantinePersistedRoomGraph,
  readQuarantinedRoomGraph,
  roomGraphProblem,
  type PersistedRoomLoad,
  type QuarantineOutcome,
  type QuarantineReason,
  type QuarantinedRoomGraph,
  type RoomSizeField,
  type StorageLike,
} from './roomGraph';
export {
  IMPORT_NOT_A_ROOM_MESSAGE,
  PLAN_SNIFF_BYTES,
  PlanFileError,
  checkPlanFile,
  looksLikeDwg,
  looksLikeDxf,
  type PlanFileCheck,
  type PlanFileKind,
  type PlanFileRejection,
} from './dwgImport';
export { clearProjectFromIdb } from './projectIO';
export { MJS_NATIVE_CONFIRM_HINT, mjsGuardPrompt, parseMjsGuardMessage } from './mjsGuardrails';
export type { InteractionMode, RoomPointerHit } from './RoomVibezViewer';
export type * from './types';
