import { pathToFileURL } from 'node:url';
import { chromium } from '/Users/adrian/Desktop/Room Vibez/v2/hackathon-3d-viewer/node_modules/playwright/index.mjs';
const URL_ = pathToFileURL('/Users/adrian/Desktop/Room Vibez/v2/prototypes/room-vibez-planner-flows/index.html').href;
const browser = await chromium.launch({ channel: 'chrome', args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 1280, height: 800 } }); const page = await ctx.newPage(); await page.goto(URL_); await page.waitForTimeout(800);
const visibleButtons = () => page.evaluate(() => [...document.querySelectorAll('.screen.active button')].filter((b) => b.getClientRects().length).map((b) => b.innerText.replace(/\s+/g, ' ').trim()));
const honesty = () => page.evaluate(() => { const t = document.body.innerText; return ['Prototype · nothing is saved', 'Click-through prototype · no real accounts', 'Nothing is sent or saved.', "This demo doesn't read your file.", 'Demo only. This animation is simulated.', 'Sample result:', 'Every file gives this same example.', 'placeholder prices'].filter((s) => t.includes(s)); });
const res = {};
res.focusAtLoad = await page.evaluate(() => document.activeElement.tagName);
res.role = { honesty: await honesty(), chips: await page.evaluate(() => !!document.querySelector('.screen.active .steps')) };
await page.click('.role-card[data-role=consumer]'); await page.click('#btnContinueAuth');
res.project = { honesty: await honesty(), chips: await page.evaluate(() => !!document.querySelector('.screen.active .steps')) };
await page.click('#btnCreateProject');
res.planBeforeFile = { visibleButtons: await visibleButtons(), drawItMyselfVisible: await page.locator('#btnManualDraw').isVisible(), honesty: await honesty(), chips: await page.evaluate(() => !!document.querySelector('.screen.active .steps')) };
await page.click('.file-chip[data-fmt=JPG]'); await page.locator('#confirmCard').waitFor({ state: 'visible', timeout: 8000 });
res.planAfterFile = { drawItMyselfVisible: await page.locator('#btnManualDraw').isVisible(), honesty: await honesty() };
await page.click('#btnManualDraw'); await page.waitForTimeout(2500);
res.edit = { honesty: await honesty(), chips: await page.evaluate(() => !!document.querySelector('.screen.active .steps')) };
await page.click('#btnOpenBom');
res.partsList = { honesty: await honesty(), chips: await page.evaluate(() => !!document.querySelector('.screen.active .steps')) };
console.log(JSON.stringify(res, null, 1));
await browser.close();
